spring.application.name=cpohubserver
spring.data.mongodb.uri=mongodb+srv://evgtestmongodb:LB3DLVNXegANeS7w@cluster0.cdrnenc.mongodb.net/EVG-CPO-HUB?ssl=true

# spring.data.mongodb.uri=mongodb+srv://evgtestmongodb:LB3DLVNXegANeS7w@cluster0.cdrnenc.mongodb.net/EVG-CPO-HUB-TEST?ssl=true
server.port=8080
management.endpoint.health.show-details=always
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.core.Query=DEBUG

#Redis Configuration
spring.redis.host=redis-18696.c262.us-east-1-3.ec2.redns.redis-cloud.com
spring.redis.port=18696
spring.redis.password=S4nIuJJ5HiHvfJvlhxvNzgu2OFWHqpgL

cpohub.url=http://192.168.123.94:8082

spring.output.ansi.enabled=ALWAYS